config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'products#index'
  resources :orders
  resources :products do
    member do
      get 'add_to_order', to: 'products#add_to_order', as: :add_to_order
      get 'remove_from_order', to: 'products#remove_from_order', as: :remove_from_order
      get 'remove_all_from_order', to: 'products#remove_all_from_order', as: :remove_all_from_order
    end

  end

end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id             :integer          not null, primary key
#  shipping_cost  :decimal(, )
#  packaging_cost :decimal(, )
#  description    :text
#  buyer_name     :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  total_price    :decimal(, )
#  total_cost     :decimal(, )
#  discount       :decimal(, )
#  full_price     :decimal(, )
#

class Order < ActiveRecord::Base
  belongs_to :user
  has_many :products, through: :order_product
  has_many :order_products

  scope :by_year, -> (year) { where("extract( YEAR FROM created_at) = ?", year) }
  scope :by_month, -> (month) { where("extract( MONTH FROM created_at) = ?", month) }

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_order, only: [:show, :edit, :destroy]
  def index
    @orders = Order.all
  end

  def show
  end

  def edit
  end

  def destroy
    if @order.destroy
      flash[:notice] = 'Order deleted'
    else
      flash[:alert] = 'Fail to delete order'
    end
    redirect_to orders_path
  end
  def create
   total_price = order_params[:full_price].to_i - order_params[:discount].to_i
   order = Order.new(order_params.merge({total_price: total_price}))
   order.total_cost = order_params[:shipping_cost].to_i + order_params[:packaging_cost].to_i + order_params[:total_cost].to_i
   if order.save
     current_user.cart.cart_products.each do |item|
       OrderProduct.create(product_id: item.product.id, order_id: order.id, amount: item.amount)

       updated_stock = item.product.stock - item.amount
       item.product.stock = updated_stock
       item.product.save
     end
   end
   current_user.cart.clear
   current_user.cart.save
   redirect_to orders_path, notice: 'Order created'
  end

  private

  def order_params
    params.require(:order).permit(:buyer_name, :shipping_cost, :packaging_cost, :description, :full_price, :total_cost, :discount)
  end

  def find_order
    @order = Order.find(params[:id])
  end
end

app/helpers/order_helper.rb
module OrderHelper
  def total_price(order)

  end
  
  def cal_rev(order)
    order.total_price.to_i - order.total_cost.to_i
  end
end

app/views/orders/_order.html.erb
<tr>
  <td>
    <%= order.id%>
  </td>
  <td>
    <%= cal_rev(order) %>
  </td>
  <td>
    <%= order.total_price%>
  </td>
  <td>
    <%= order.full_price%>
  </td>
  <td>
    <%= order.discount%>
  </td>
  <td>
    <%= order.total_cost%>
  </td>
  <td>
    <%= order.buyer_name%>
  </td>
  <td class='text-center'>
    <%= link_to 'Show', order_path(order.id), class: 'btn btn-success'%>
    <%= link_to 'Edit', edit_order_path(order.id), class: 'btn btn-warning'%>
    <%= link_to 'Delete', order_path(order.id), method: 'delete', class: 'btn btn-danger'%>
  </td>
</tr>

app/views/orders/_order_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h2 class='text-left'>New Order</h2>
      <%= form_for(@order, url: orders_path(@order)) do |f|  %>
        <%= f.hidden_field :full_price, value: @cart.total_price %>
        <%= f.hidden_field :total_cost, value: @cart.total_cost %>
        <div class="form-group">
          <%= f.label 'Buyer Name' %>
          <%= f.text_field :buyer_name, class: 'form-control', autocomplete: 'off' %>
        </div>
        <div class="form-group">
          <%= f.label 'Shipping Cost' %>
          <%= f.number_field :shipping_cost, class: 'form-control', autocomplete: 'off' %>
        </div>
        <div class="form-group">
          <%= f.label 'Packaging Cost' %>
          <%= f.number_field :packaging_cost, class: 'form-control', autocomplete: 'off', min: 0 %>
        </div>
        <div class="form-group">
          <%= f.label 'Discount' %>
          <%= f.number_field :discount, class: 'form-control', autocomplete: 'off' %>
        </div>
        <div class="form-group">
          <%= f.label 'Note' %>
          <%= f.text_field :description, class: 'form-control', autocomplete: 'off' %>
        </div>
        <div class="text-center">
          <%= f.submit 'สร้าง Order', class: 'btn btn-default btn-primary' %>
          <%= link_to 'Clear', remove_all_from_order_product_path(99), class: 'btn btn-default'%>
        </div>
      <% end %>
    </div>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2>Ordered Products</h2>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-xs-3"><b>Name</b></div>
            <div class="col-xs-3"><b>Price</b></div>
            <div class="col-xs-3"><b>Cost</b></div>
            <div class="col-xs-1"><b>Amnt.</b></div>
          </div>
          <%= render partial: 'orders/order_items', collection: @cart.cart_products, as: :item %>
        </div>
        <div class="panel-footer">
          <div class="row">
            <div class="col-md-6">
              <h4>Total price: <%= @cart.total_price %></h4>
            </div>
            <div class="col-md-6">
              <h4>Total cost: <%= @cart.total_cost %></h4>
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/orders/_order_items.html.erb
<% if item.amount > 0%>
  <div class="row">
    <div class="col-md-3"><%= item.product.name %></div>
    <div class="col-md-3"><%= "#{item.product.price} B" %></div>
    <div class="col-md-3"><%= "#{item.product.cost} B" %></div>
    <div class="col-md-1"><%= item.amount %></div>
    <div class="col-md-1">
      <%= link_to 'X', remove_from_order_product_path(item.product.id), method: 'get', class: 'btn btn-danger btn-xs', style: 'font-size: 8px;'%>
    </div>
  </div>
<% end %>

app/views/orders/_order_products.html.erb
<% if item.amount > 0%>
  <div class="row">
    <div class="col-md-4"><%= item.product.name %></div>
    <div class="col-md-3"><%= "#{item.product.price} B" %></div>
    <div class="col-md-3"><%= "#{item.product.cost} B" %></div>
    <div class="col-md-2"><%= item.amount %></div>
  </div>
<% end %>

app/views/orders/_summary.html.erb
<tr>
  <td>
  </td>
</tr>

app/views/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading"><h1 class='text-center'>Summary</h1></div>
      <div class="panel-body">
        <table class="table table-bordered">
          <tr>
            <th>Month/Year</th>
            <th>Total Revenue</th>
            <th>Total Profit</th>
            <th>Total Cost</th>
          </tr>
          <%= render partial: 'summary', collection: @this_year, as: :order %>
        </table>
      </div>
    </div>
  </div>
  <h1 class='text-center'> Order History </h1>
  <table class="table table-bordered table-striped">
    <tr>
      <th><h3>Order ID</h3></th>
      <th><h3>Revenue</h3></th>
      <th><h3>Total Price</h3></th>
      <th><h3>Full Price</h3></th>
      <th><h3>Discount</h3></th>
      <th><h3>Total Cost</h3></th>
      <th><h3>Buyer Name</h3></th>
      <th><h3>Options</h3></th>
    </tr>
    <tr>
      <td class="text-center" colspan=100%>
        <%= link_to 'Add new order', products_path, class: 'btn btn-success'%>
      </td>
    </tr>
    <%= render partial: 'order', collection: @orders, as: :order %>
  </table>
</div>

app/views/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading"><h4>[Order ID] : <%= @order.id%>   [Buyer] : <%= @order.buyer_name%></h4></div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-4"><b>Name</b></div>
            <div class="col-md-3"><b>Price</b></div>
            <div class="col-md-3"><b>Cost</b></div>
            <div class="col-md-2"><b>Amnt.</b></div>
          </div>
          <%= render partial: 'order_products', collection: @order.order_products, as: :item %>
        </div>
        <div class="panel-footer">
          <div class="row">
            <div class="col-md-6">
              <div class="row">
                <div class="col-md-6">
                  <b>Full price: </b> <%= @order.full_price %>
                </div>
                <div class="col-md-6">
                  <b>Discount: </b> <%= @order.discount %>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <b>Shipping cost: </b> <%= @order.shipping_cost %>
                </div>
                <div class="col-md-6">
                  <b>Packaging cost: </b> <%= @order.packaging_cost %>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <h4>Total price: <small><%= @order.total_price %></small></h4>
                </div>
                <div class="col-md-6">
                  <h4>Total cost: <small><%= @order.total_cost %></small></h4>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <h3>Revenue: <%= cal_rev(@order)%></h3>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <h4> Description </h4>
              <p><%= @order.description %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>