config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'products#index'
  resources :orders
  resources :products do
    member do
      get 'add_to_order', to: 'products#add_to_order', as: :add_to_order
      get 'remove_from_order', to: 'products#remove_from_order', as: :remove_from_order
      get 'remove_all_from_order', to: 'products#remove_all_from_order', as: :remove_all_from_order
    end

  end

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  price       :decimal(, )
#  stock       :integer
#  cost        :decimal(, )
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ActiveRecord::Base
  has_many :orders, through: :order_product
  has_many :order_products
  has_many :cart_products
  has_many :carts, through: :cart_product

  validates :name, presence: true
  validates :price, presence: true
  validates :stock, presence: true
  validates :cost, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.order(:name)
    @order = Order.new
    @cart = current_user.cart
    @cart ||= Cart.create(user_id: current_user.id)
  end

  def new
    @product = Product.new
  end

  def remove_all_from_order
    current_user.cart.clear
    current_user.cart.save
    redirect_to products_path, notice: 'Order cleared'
  end

  def remove_from_order
    if current_user.cart.present?
      current_user.cart.remove(params[:id])
    end
    redirect_to products_path, notice: 'Remove a product from order'
  rescue ActiveRecord::RecordNotFound
    redirect_to products_path, alert: 'There is no such product'
  end

  def add_to_order
    cart = current_user.cart
    if cart.present?
      cart.add(params[:id])
    else
      cart = Cart.new()
      if cart.save
        cart.add(params[:id])
      end
    end
    redirect_to products_path, notice: 'Added product to order'
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    product =Product.find(params[:id])
    if product.update(product_params)
      redirect_to products_path, notice: 'Product updated'
    else
      redirect_to products_path, alert: 'Fail to update product'
    end
  end

  def destroy
    product = Product.find(params[:id])
    if product.destroy
      flash[:notice] = "Product deleted"
    else
      flash[:alert] ="Cannot delete product"
    end
    redirect_to products_path
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = 'Product created!'
    else
      flash[:alert] =  'Missing parameter. Try again'
    end
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :stock, :cost, :description)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cal_total(ar,type)
    total = 0
    return total if ar.blank?
    ar.each do |i|
      total += i[type].to_i
    end
    total
  end
end

app/views/products/_product.html.erb
<tr>
  <td>
    <%= p.name%>
  </td>
  <td>
    <%= p.price%>
  </td>
  <td>
    <%= p.cost%>
  </td>
  <%if p.stock < 3 && p.stock > 0%>
    <td class='warning'>
  <%elsif p.stock == 0%>
    <td class='danger'>
  <%else%>
    <td>
  <%end%>
    <%= p.stock%>
  </td>
  <td>
    <%= p.description%>
  </td>
  <td class='text-center'>
    <%= link_to 'Add to order', add_to_order_product_path(p.id) , class: 'btn btn-success'%>
    <%= link_to 'Edit', edit_product_path(p.id), class: 'btn btn-warning'%>
    <%= link_to 'Delete', product_path(p.id), method: 'delete', class: 'btn btn-danger'%>
  </td>
</tr>

app/views/products/_product_form.html.erb
<div class="container">
  <div class="row">
    <h2 class='text-center'>New Product</h2>
    <div class="col-md-4 col-md-offset-4">
      <%= form_for @product do |f|  %>
        <div class="form-group">
          <%= f.label 'Product Name' %>
          <%= f.text_field :name, class: 'form-control', autocomplete: 'off' %>
        </div>
        <div class="form-group">
          <%= f.label 'Price' %>
          <%= f.number_field :price, class: 'form-control', autocomplete: 'off', min: 0 %>
        </div>
        <div class="form-group">
          <%= f.label 'Stock' %>
          <%= f.number_field :stock, class: 'form-control', autocomplete: 'off', min: 0 %>
        </div>
        <div class="form-group">
          <%= f.label 'Cost' %>
          <%= f.number_field :cost, class: 'form-control', autocomplete: 'off', min: 0 %>
        </div>
        <div class="form-group">
          <%= f.label 'Note' %>
          <%= f.text_field :description, class: 'form-control', autocomplete: 'off' %>
        </div>
        <div class="text-center">
          <%= f.submit 'สร้าง Product', class: 'btn btn-default btn-primary'  %>
          <%= link_to 'Back', products_path, class: 'btn btn-default' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<%= render partial: 'product_form'%>

app/views/products/index.html.erb
<div class="container" style='padding: 0 0 5%;'>
  <h1 class='text-center' style='margin-bottom:3%;'>Veronique Tool</h1>
  <table class="table table-bordered table-striped">
    <tr>
      <th><h3>Name</h3></th>
      <th><h3>Price</h3></th>
      <th><h3>Cost</h3></th>
      <th><h3>Stock</h3></th>
      <th><h3>Description</h3></th>
      <th><h3>Option</h3></th>
    </tr>
    <tr>
      <td class="text-center" colspan=100%>
        <%= link_to 'Add new product', new_product_path, class: 'btn btn-success'%>
      </td>
    </tr>
    <%= render partial: 'product', collection: @products, as: :p %>
  </table>
  <div class="row">
    <%= render 'orders/order_form'%>
  </div>
</div>

app/views/products/new.html.erb
<%= render partial: 'product_form'%>